### ISSUE TITLE
Add some jokes

### ISSUE THREAD

**Issue by Geetanjaligupta123** [UtkarshPrajapati/Random-Jokes-Generator#2]

**Comment by SRIMANKS** [comment]
i can work on this but can you add the hacktoberfest tag, what exactly should I do ?

**Comment by Hiresh23** [comment]
i can work on this but can you please add hacktoberfest tag

**Comment by vaibhavmishra4g** [comment]
hey could you assign me the task under hacktoberfest label?would love to work for the repo

**Comment by SRIMANKS** [comment]
can you assign me this

**Comment by SRIMANKS** [comment]
is the issue still open
